### PR TITLE
Still need escape characters (\) for Perl. Convoluted, but works

### PR DESCRIPTION
**Pull request by jasin**
This works for me as you intended

`Doing 'msbuild jpeg.vcxproj /t:Build /p:Configuration=Release;Platform=x64' to c:\development\build\3rdParty-build\bldlog-2.txt
Installing the jpeg built components...'`

success

### CODE REVIEW

**Comment by jasin** [comment]
@geoffmcl 

Think we should have the discussion here. Then I will --amend the commit and resubmit it. I didn't realize you was not going to like my change. Mostly because perl regex is something I try and avoid and then the added syntax of ECHO. Your thoughts appreciated to explain the situation?

The reason I added the escape characters in the way I did, was because it wasn't meant for **ECHO**, it was meant to be there for perl. Perl interpreted '<,/,>' as special characters. Therefor I was  not trying to get echo to change its behavior, just copy the line correctly to the file so perl has a valid line to execute. The above change does this for me

**Comment by geoffmcl** [comment]
@jasin I know why you added the `\`... if you read on a little I asked why is that not `^\`?

I had already quickly tested and it work, but so did mine... I seek to understand which is **the right way**... and asked if you could test the alternative, and explain...

PS: You can not amend a commit... well except the message before you push, but once pushed that is the commit, and you can add others to it, extending the PR...

Or you can delete that commit... take the file back to HEAD... and present a new commit, and thus a new PR, with just the single change... sometimes does not matter...

**Comment by jasin** [comment]
> I seek to understand which is the right way

Works here as well **both** ways. 
My logical reasoning says I just wanted echo to do it's job not escape anything. Guess another way to explain my thinking, why add something that isn't needed? What are we escaping exactly if it works? 

But a technical explanation could be helpful of future pitfalls.

**Comment by geoffmcl** [comment]
@jasin hmmm, so both work... ok... that's interesting... thanks...

Yes, I too, am not into exactly being sure what needs to be escaped in a an echo command, but somehow, I thought the primary `\` escape character, used in many scripts,  does **not**, in itself, need to be escaped more in an echo `echo` command... well, this is an ok idea...

I will certainly reflect upon this... maybe you are 100% right, and I should merge this... as is...

Alternatively, if on reflection, you present an alternate PR with the `\` escaped, as in the original, for the `^\n` escape... so any PR on this should also address that... if you fix one way, they fix the other...

Sorry for what seems like `pedantry`! I want to `understand`... improve my batch file skills... I have been writing them for a long time, but perhaps I need to learn more of the **new** cmd.exe interpreter...

If it is not required, then the PR should also fix this 2nd use of the `^` escape at the same time...

If I am wrong, sorry, you need to educate me... I will listen... what works for you should be good proof...

But offer a PR that goes 100% one way, or the other, but **not** a mixture of two ideas... if both work 100% of the time, then use the lesser, in all cases, else escape em all...

Just an idea...

**Comment by geoffmcl** [comment]
@jasin this pair of commits looks fine, and now merged... thanks...

And I will try to remember to remove the TEST JUMPS, line 136, and 438, when merging with next shortly...

**Pull request merged**
