### PR TITLE
Fixes for auto-selecting MSVC2013 Express

### PR DESCRIPTION
**Pull request by jasin**
@geoffmcl This should be much better. Git can be a real pain, learn something new everyday. Now to just remember, branch branch branch! 

1 file changes
1 commit

SANE!

### CODE REVIEW

**Comment by jasin** [comment]
Line 112 :NAMKE_FAILED

should be 

Line 112 :NMAKE_FAILED

I will let you correct instead if you don't mind

**Comment by geoffmcl** [comment]
@jasin if by **better** you mean a single commit to a single file... yes it is...

But is it **better** in a working sense? NO! It fails in my system. You missed the fact that in my system the BIN BAT is called `vcvars64.bat`... PR rejected...

But more that that - you gave yourself good advice - 

> Now to just remember, branch branch branch!

But then you didn't **branch**! ;=))

You also missed that I had switched to the `next` branch. In there the file to **fix** is `_selectMSVC.x64.bat`... note the .x64 addition... 

Do not **need** any change to the soon to die `_selectMSVC.bat` in the `master` branch... it will not exist after I merge next to master, after testing...

But all that aside, could you answer one question does `_selectMSVC.x64.bat` work for you? Why are you changing things if yes? If no, what is the problem?

The bat file already checked if an appropriate bat file existed, why did you feel the need to change this around?

Anyway, please do -
$ git checkout next
$ git pull

I have now fixed the two typos... thanks...

**Comment by geoffmcl** [comment]
PS: Just tried to pull your fork, but have a conflict in master _selelectMSVC.bat!!!

Blew that away, and now cloned fresh, and can see the modified, but rejected, `_selectMSVC.bat`, in your `selectMSVC` branch...

But as stated, the file is now `_selectMSVC.x64.bat` in the **`next`** branch... so did -

```
$ git remote add upstream git@github.com:geoffmcl/test-sg.git
$ git remote -v  # check connections
$ git fetch upstream
$ git checkout next
$ git rebase upstream/next
```

Now, scripts\d-and-c contains the **latest** `_selectMSVC.x64.bat`...

To test -

```
$ cd scripts\d-and-c
$ md temp
$ cd temp
$ copy ..\*.bat
$ make3rd.x64
# if that succeeds... sometimes need to run it a few times, then
$ d-and-c.x64
```

Appreciate any feedback... 

PPS: I will look at your d-and-c.bat changes for an additional option, but obviously that now has to be applied to d-and-c.x64.bat...

**Comment by jasin** [comment]
**BIG FAT EDIT:** I AM ASSUMING WE WANT TO AUTO-SELECT THE %BUILD_BITS%,  otherwise we should be calling this, **set-and-validateMSVC.bat**

> But all that aside, could you answer one question does _selectMSVC.x64.bat work for you? Why are you changing things if yes? If no, what is the problem?

It fails check #1, It passes check #2, but this assumes I am using amd64 what about ia64? 

because, and this is only my personal preference and maybe you see it differently. 
_selectMSVC.x64.bat on NEXT branch. I did not miss this, I refuse to move forward until I understand! 

$Git checkout -b next
Line 21 @set BUILD_BITS=%PROCESSOR_ARCHITECTURE%
**THIS CAN NEVER BE x86_amd64**
Line 41 @IF /i %BUILD_BITS% EQU x86_amd64
**NEVER GOING TO PASS**
Line 46 @IF /i %BUILD_BITS% EQU amd64
**PASSES and sets incorrect MSVCBIN**
Line 49 @set "MSVCBIN=%VS_PATH%\VC\bin\%BUILD_BITS%\vcvars64.bat"

Line 67 @set BUILD_BITS=x86_amd64
**This will fail to set x86_ia64, which would be IA64 using MSVC Express**

To me you have only covered AMD64 and assumed x86_amd64 when everything else fails(which it will because you set %MSVCBIN% incorrectly when %PROCESSOR_ARCHITECTURE% EQU AMD64 and the **USER** is compiling with the **Express** version of MSVC.

I **want** to correctly set %MSVCBIN%. If we can validate that IA64 also uses vcvars64.bat(same as AMD64 does under MSVC professional) then using my logic, it is one change to one line of code to make it work. Just s/%BUILD_BITS&%/64

from
@set "MSVCBIN=%VS_PATH%\VC\bin\%BUILD_BITS%\vcvars%BUILD_BITS%.bat"
to
@set "MSVCBIN=%VS_PATH%\VC\bin\%BUILD_BITS%\vcvars64.bat"

**Comment by jasin** [comment]
> PS: Just tried to pull your fork, but have a conflict in master _selelectMSVC.bat!!!
> 
> Blew that away, and now cloned fresh, and can see the modified, but rejected, _selectMSVC.bat, in your selectMSVC branch...

HOW??? I thought you just told me that we should create branches to work in and then merge **new** features back to the master branch. **BUT** before you do that with,your local repo, rebase to upstream/master(so local master is same as upstream/master and rebase **new** feature branch). This is where I assume your changes with be merged into(upstream/master)

I am tracking your master with my master. There is no changes in my master/_selectMSVC.bat file. I never touched it! How that fails is beyond my capacity to understand. 

I also NEVER merged anything from either of my branches to my master. It still is and should be a mirror copy of the git clone I did last night all over again. Utter non-sense to me if that does not work

**Comment by jasin** [comment]
Ok, moving on to _selectMSVC,x64.bat

**Pull request closed without merging**
